//! Cross-language conformance vectors for the id layout.
//!
//! The layout has been written four times -- here, in the PhysX bridge's C++,
//! in the client's TypeScript, and in the wire encoder -- and the copies
//! drifted, silently corrupting island membership for a whole match. Review did
//! not catch it because each copy is individually plausible.
//!
//! So the copies get a shared oracle instead. This test regenerates
//! `blast/spec/destruction-ids.json` from the Rust layout and fails if it
//! differs from what is committed, which does two things: a layout change
//! cannot land without a deliberate diff to the vectors, and every non-Rust
//! port can assert against the same file rather than against a reading of the
//! comments.
//!
//! Set `BLAST_UPDATE_ID_VECTORS=1` to rewrite the file after an intended change.
#![cfg(feature = "scenarios")]

use std::path::PathBuf;

use blast_stress_solver::ids::{IdLayout, DEFAULT_LAYOUT, ID_BITS, ID_MASK, NAMESPACE_MASK};

fn spec_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../spec/destruction-ids.json")
}

/// Real extremes from the shipped packs, not round numbers: a district pack is
/// 15,918 nodes in one structure and a dense downtown 74,543 bonds. Round
/// numbers would have missed both of the field-width bugs this file exists for.
fn structures() -> Vec<u32> {
    vec![0, 1, 5, 15, DEFAULT_LAYOUT.max_structures() - 1]
}
fn nodes() -> Vec<u32> {
    vec![0, 1, 203, 4_095, 4_096, 9_594, 15_917, 15_918, 24_104, DEFAULT_LAYOUT.max_nodes_per_structure() - 1]
}
fn bonds() -> Vec<u32> {
    vec![0, 545, 65_535, 65_536, 74_542, 74_543, DEFAULT_LAYOUT.max_bonds_per_structure() - 1]
}
fn serials() -> Vec<u32> {
    vec![0, 1, 42, 65_535, 65_536, 4_194_302, DEFAULT_LAYOUT.max_island_serials() - 1]
}

fn generate(l: &IdLayout) -> String {
    let mut s = String::new();
    s.push_str("{\n");
    s.push_str("  \"_comment\": \"Generated by blast-stress-solver-rs/tests/id_layout_conformance_test.rs. Do not hand-edit; every port asserts against this file.\",\n");
    s.push_str("  \"_note_for_javascript_ports\": \"Use arithmetic, not bitwise operators. JS bitwise ops coerce to int32, so 0x80000000 | x is negative.\",\n");
    s.push_str("  \"layout\": {\n");
    s.push_str(&format!("    \"namespace\": {},\n", l.namespace()));
    s.push_str(&format!("    \"id_bits\": {ID_BITS},\n"));
    s.push_str(&format!("    \"id_mask\": {ID_MASK},\n"));
    s.push_str(&format!("    \"namespace_mask\": {NAMESPACE_MASK},\n"));
    s.push_str(&format!("    \"node_bits\": {},\n", l.max_nodes_per_structure().trailing_zeros()));
    s.push_str(&format!("    \"bond_bits\": {},\n", l.max_bonds_per_structure().trailing_zeros()));
    s.push_str(&format!("    \"serial_bits\": {},\n", l.max_island_serials().trailing_zeros()));
    s.push_str(&format!("    \"max_structures\": {},\n", l.max_structures()));
    s.push_str(&format!("    \"max_nodes_per_structure\": {},\n", l.max_nodes_per_structure()));
    s.push_str(&format!("    \"max_bonds_per_structure\": {},\n", l.max_bonds_per_structure()));
    s.push_str(&format!("    \"max_island_serials\": {}\n", l.max_island_serials()));
    s.push_str("  },\n");

    let mut section = |name: &str, rows: Vec<String>, last: bool| {
        s.push_str(&format!("  \"{name}\": [\n"));
        for (i, r) in rows.iter().enumerate() {
            s.push_str(&format!("    {r}{}\n", if i + 1 == rows.len() { "" } else { "," }));
        }
        s.push_str(if last { "  ]\n" } else { "  ],\n" });
    };

    let mut rows = Vec::new();
    for st in structures() {
        for n in nodes() {
            rows.push(format!("{{ \"structure\": {st}, \"node\": {n}, \"id\": {} }}", l.chunk_id(st, n)));
        }
    }
    section("chunk_ids", rows, false);

    let mut rows = Vec::new();
    for st in structures() {
        for b in bonds() {
            rows.push(format!("{{ \"structure\": {st}, \"bond\": {b}, \"id\": {} }}", l.bond_id(st, b)));
        }
    }
    section("bond_ids", rows, false);

    let mut rows = Vec::new();
    for st in structures() {
        for sr in serials() {
            rows.push(format!(
                "{{ \"structure\": {st}, \"serial\": {sr}, \"entity\": {} }}",
                l.body_entity(st, sr)
            ));
        }
    }
    section("body_entities", rows, true);

    s.push_str("}\n");
    s
}

#[test]
fn the_committed_vectors_match_the_layout() {
    let generated = generate(&DEFAULT_LAYOUT);
    let path = spec_path();
    if std::env::var("BLAST_UPDATE_ID_VECTORS").is_ok() {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, &generated).unwrap();
        return;
    }
    let committed = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!("{}: {e}. Run with BLAST_UPDATE_ID_VECTORS=1 to create it.", path.display())
    });
    assert_eq!(
        committed, generated,
        "the id layout changed without updating {}. Every port asserts against \
         that file, so landing this silently renumbers entities mid-match. If \
         the change is intended, rerun with BLAST_UPDATE_ID_VECTORS=1 and review \
         the diff.",
        path.display()
    );
}

/// Round-tripping every vector, so the file pins decode as well as encode.
#[test]
fn every_vector_round_trips() {
    let l = DEFAULT_LAYOUT;
    for st in structures() {
        for n in nodes() {
            assert_eq!(l.chunk_id_parts(l.chunk_id(st, n)), (st, n));
        }
        for b in bonds() {
            assert_eq!(l.bond_id_parts(l.bond_id(st, b)), (st, b));
        }
        for sr in serials() {
            let e = l.body_entity(st, sr);
            assert!(l.is_body_entity(e));
            assert_eq!(l.body_entity_parts(e), (st, sr));
        }
    }
}

/// No two vectors of the same kind may collide -- a collision is the exact
/// symptom of a field that is too narrow.
#[test]
fn no_two_vectors_collide() {
    use std::collections::HashMap;
    let l = DEFAULT_LAYOUT;

    let mut seen: HashMap<u32, (u32, u32)> = HashMap::new();
    for st in structures() {
        for n in nodes() {
            let id = l.chunk_id(st, n);
            if let Some(prev) = seen.insert(id, (st, n)) {
                panic!("chunk id {id} claimed by both {prev:?} and ({st}, {n})");
            }
        }
    }
    let mut seen: HashMap<u32, (u32, u32)> = HashMap::new();
    for st in structures() {
        for b in bonds() {
            let id = l.bond_id(st, b);
            if let Some(prev) = seen.insert(id, (st, b)) {
                panic!("bond id {id} claimed by both {prev:?} and ({st}, {b})");
            }
        }
    }
    let mut seen: HashMap<u32, (u32, u32)> = HashMap::new();
    for st in structures() {
        for sr in serials() {
            let e = l.body_entity(st, sr);
            if let Some(prev) = seen.insert(e, (st, sr)) {
                panic!("body entity {e} claimed by both {prev:?} and ({st}, {sr})");
            }
        }
    }
}
